### ISSUE TITLE
Migrate from 2.4 to 3.0 

### ISSUE THREAD

**Issue by julien26320** [neutmute/emgucv#1]
Hello, How are you ?
I am looking the method to get Vector of points from CudaGoodFeatureToTrackDetector 
and CudaDensePyrLKOpticalFlow like the method TestCudaFASTDetector inside the class AutoTestCuda.cs located on the following link
https://github.com/neutmute/emgucv/blob/master/Emgu.CV.Test/AutoTestCuda.cs

Sincerely, Julien Taste.

**Comment by neutmute** [comment]
Hi Julian - emgu CV isn't actually my repo. the owner/maintainer has it hosted on http://sourceforge.net/projects/emgucv/
I just have it hosted here for my own convenience - it doesn't always track master on the main repo
