### ISSUE TITLE
Emgu.CV.Unity errors

### ISSUE THREAD

**Issue by reidblomquist** [neutmute/emgucv#3]
Could you please make the readme(s) here a bit more robust? Have attempted to use the bash scripts to both copy Unity assets and demo assets over; as well as imported Emgu .dll and have yet to get a passing build together. (Latest Unity5 release)

**Comment by neutmute** [comment]
Hi there - this is a clone of the main project on sourceforge - I am not the project owner

**Comment by reidblomquist** [comment]
Thanks for chiming in neutmute! Found their private git and the git build instructions. Would you be open to me forking, PRing, and bolstering repo documentation to be more 1:1 with their wiki documentation?

**Comment by neutmute** [comment]
It is a good idea as the readme is well out of date compared to the wiki but you should PR back to Canming who is the owner/maintainer on [sourceforge](http://sourceforge.net/projects/emgucv/). 
My repo here is a slave to his. 
Canminghas accepted a PR of mine before so you should get it accepted.
Be warned the sourceforge git web interface is very frustrating! :)
