### ISSUE TITLE
Error when building Emgu.CV.Example

### ISSUE THREAD

**Issue by JamieTabone** [neutmute/emgucv#4]
![image](https://cloud.githubusercontent.com/assets/6746603/15231347/d7537114-189a-11e6-8490-56f38f13831d.png)

I have this error repeatedly when I try to build the solution. Can you please suggest what can be the problem?

Thank you

**Comment by neutmute** [comment]
Hi James - EmguCV isn't my project, this is just a clone. EmguCV is hosted at https://sourceforge.net/projects/emgucv/
He has docs there - the build isn't easy but if you follow the instructions carefully it does work
