### ISSUE TITLE
Some errors while building Emgu.CV.Example.iOS project

### ISSUE THREAD

**Issue by yehe01** [neutmute/emgucv#6]
Hi,

I am trying to build the Xamarin iOS project from source. What I have done is to change the Emgu.CV.World.iOS reference to the one downloaded from the component store rather than the source code project because of the license issue.

The build log is as follows:

Done building project

"/Users/xxx/projects/emgucv/Emgu.CV.Example/iOS/Emgu.CV.Example.iOS.csproj".-- FAILED

Build FAILED.
Errors:

/Users/xxx/projects/emgucv/Emgu.CV.Example/iOS/Emgu.CV.Example.iOS.csproj (Build) ->
/Library/Frameworks/Mono.framework/Versions/4.4.2/lib/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

../FeatureMatching/DrawMatches.cs(29,47): error CS1061: Type 'Emgu.CV.Mat' does not contain a definition for 'GetUMat' and no extension method 'GetUMat' of type 'Emgu.CV.Mat' could be found. Are you missing an assembly reference?

../FeatureMatching/DrawMatches.cs(30,53): error CS1061: Type 'Emgu.CV.Mat' does not contain a definition for 'GetUMat' and no extension method 'GetUMat' of type ;Emgu.CV.Mat' could be found. Are you missing an assembly reference?

FaceDetectionDialogViewController.cs(38,27): error CS1501: No overload for method 'Detect' takes '7' arguments

PedestrianDetectionDialogViewController.cs(33,57): error CS1501: No overload for method 'Find' takes '3' arguments

	 0 Warning(s)
	 4 Error(s)

For the last two errors, it is easy to see from the source code that the method call and definition are inconsistent:

```c#
DetectFace.Detect(
image.Mat,
"haarcascade_frontalface_default.xml",
"haarcascade_eye.xml",
faces,
eyes, 
false,
out processingTime
);
```

```c#
public static void Detect(
IInputArray image, String faceFileName, String eyeFileName,
List<Rectangle> faces, List<Rectangle> eyes,
out long detectionTime)
```

**Comment by yehe01** [comment]
I guess the first two errors are because the library in the component store is not up to date.

**Comment by neutmute** [comment]
this isn't my project - the real one is on sourceforge. this is just a clone
