### ISSUE TITLE
How can I build the example project without a business license?

### ISSUE THREAD

**Issue by yehe01** [neutmute/emgucv#7]
Hi,

When I build the example project, it will report this error:
`This package do not contain necessary binary for Xamarin iOS Native Binding Library. Emgu CV for iOS Commercial License is required. Missing /Users/yehe/projects/emgucv/Emgu.CV/PInvoke/iOS/libemgucv.a`

Is there a way to build example without buying a business license? I am currently building examples using the library from Xamarin component store, but it seems it is not up to date anymore. See #6

**Comment by neutmute** [comment]
this isn't my project - the real one is on sourceforge. this is just a clone
