### ISSUE TITLE
videowriter don't works

### ISSUE THREAD

**Issue by top1st** [neutmute/emgucv#8]
_videoW = new VideoWriter(@"d:\temp.avi", 25, VideoWriter.Fourcc('D', 'I', 'V', 'X'), frame.Size, true);
frame = capture1.QueryFrame();
_videoW.Write(frame);

Please give me sample. it don't work never save any data...

**Comment by neutmute** [comment]
This is a personal mirror of the actual project at http://sourceforge.net/projects/emgucv/ This mirror almost always will not be current
