### ISSUE TITLE
Tesseract Recognize Method does not have overload method that accept 1 parameter

### ISSUE THREAD

**Issue by UNICASTERSOL** [neutmute/emgucv#9]
Hello, 

I tried to run your example using the the latest Emgu library and it seems that I encountered compilation error as per title.

Did Recognize method overload method has been removed?

Thanks.

Simon

**Comment by neutmute** [comment]
This is a personal mirror of the actual project at http://sourceforge.net/projects/emgucv/ This mirror almost always will not be current
